# Generated by Django 4.1.4 on 2023-01-06 08:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reverse_ssh_api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_arch', models.TextField()),
                ('cpu_bits', models.IntegerField(validators=[reverse_ssh_api.validators.ValueInListValidator([32, 64])])),
                ('cpu_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('cpu_arch_string_raw', models.TextField()),
                ('cpu_vendor_id_raw', models.TextField()),
                ('cpu_brand_raw', models.TextField()),
                ('cpu_hz_actual_friendly', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='GPUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_index', models.IntegerField()),
                ('gpu_name', models.TextField()),
                ('gpu_brand', models.TextField()),
                ('gpu_nvml_version', models.TextField()),
                ('gpu_driver_version', models.TextField()),
                ('gpu_vbios_version', models.TextField()),
                ('gpu_multi_gpu_board', models.BooleanField()),
                ('gpu_display_mode', models.BooleanField()),
                ('gpu_display_active', models.BooleanField()),
                ('gpu_persistence_mode', models.BooleanField()),
                ('gpu_compute_mode', models.TextField()),
                ('gpu_power_management_mode', models.BooleanField()),
                ('gpu_power_management_limit', models.IntegerField()),
                ('gpu_temperature_shutdown', models.IntegerField()),
                ('gpu_temperature_slowdown', models.IntegerField()),
                ('gpu_enforced_power_limit', models.IntegerField()),
                ('gpu_max_clock_info_graphics', models.IntegerField()),
                ('gpu_max_clock_info_sm', models.IntegerField()),
                ('gpu_max_clock_info_mem', models.IntegerField()),
                ('gpu_max_clock_info_video', models.IntegerField()),
                ('gpu_memory_info_total', models.BigIntegerField()),
                ('gpu_bar1_memory_info_total', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MemorySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_total', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservedPort',
            fields=[
                ('reserved_port', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)])),
            ],
        ),
        migrations.CreateModel(
            name='MemoryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_used', models.BigIntegerField()),
                ('memory_available', models.BigIntegerField()),
                ('memory_free', models.BigIntegerField()),
                ('swap_total', models.BigIntegerField()),
                ('swap_used', models.BigIntegerField()),
                ('swap_free', models.BigIntegerField()),
                ('memory_update_time', models.DateTimeField(auto_now=True)),
                ('memory_spec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reverse_ssh_api.memoryspec')),
            ],
        ),
        migrations.CreateModel(
            name='GPUStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_power_usage', models.IntegerField()),
                ('gpu_temperature', models.IntegerField()),
                ('gpu_fan_speed', models.IntegerField()),
                ('gpu_clock_info_graphics', models.BigIntegerField()),
                ('gpu_clock_info_sm', models.BigIntegerField()),
                ('gpu_clock_info_mem', models.BigIntegerField()),
                ('gpu_clock_info_video', models.BigIntegerField()),
                ('gpu_memory_info_free', models.BigIntegerField()),
                ('gpu_memory_info_used', models.BigIntegerField()),
                ('gpu_bar1_memory_info_free', models.BigIntegerField()),
                ('gpu_bar1_memory_info_used', models.BigIntegerField()),
                ('gpu_utilization_gpu', models.IntegerField()),
                ('gpu_utilization_memory', models.IntegerField()),
                ('gpu_utilization_encoder', models.IntegerField()),
                ('gpu_utilization_decoder', models.IntegerField()),
                ('gpu_update_time', models.DateTimeField(auto_now=True)),
                ('gpu_spec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reverse_ssh_api.gpuspec')),
            ],
        ),
        migrations.CreateModel(
            name='CPUStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_core', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(127)])),
                ('cpu_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('cpu_update_time', models.DateTimeField(auto_now=True)),
                ('cpu_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reverse_ssh_api.cpuspec')),
            ],
        ),
        migrations.CreateModel(
            name='UsedPort',
            fields=[
                ('used_port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reverse_ssh_api.reservedport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_port', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='memorystat',
            index=models.Index(fields=['memory_spec'], name='reverse_ssh_memory__562046_idx'),
        ),
        migrations.AddIndex(
            model_name='memorystat',
            index=models.Index(fields=['memory_update_time'], name='reverse_ssh_memory__77857c_idx'),
        ),
        migrations.AddField(
            model_name='memoryspec',
            name='used_port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reverse_ssh_api.usedport'),
        ),
        migrations.AddIndex(
            model_name='gpustat',
            index=models.Index(fields=['gpu_spec'], name='reverse_ssh_gpu_spe_753c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='gpustat',
            index=models.Index(fields=['gpu_update_time'], name='reverse_ssh_gpu_upd_0515db_idx'),
        ),
        migrations.AddField(
            model_name='gpuspec',
            name='used_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reverse_ssh_api.usedport'),
        ),
        migrations.AddIndex(
            model_name='cpustat',
            index=models.Index(fields=['cpu_spec'], name='reverse_ssh_cpu_spe_bad4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='cpustat',
            index=models.Index(fields=['cpu_update_time'], name='reverse_ssh_cpu_upd_165e4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cpustat',
            unique_together={('cpu_spec', 'cpu_core')},
        ),
        migrations.AddField(
            model_name='cpuspec',
            name='used_port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reverse_ssh_api.usedport'),
        ),
        migrations.AddIndex(
            model_name='usedport',
            index=models.Index(fields=['user'], name='reverse_ssh_user_id_fa0a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryspec',
            index=models.Index(fields=['used_port'], name='reverse_ssh_used_po_84d8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='gpuspec',
            index=models.Index(fields=['used_port'], name='reverse_ssh_used_po_d3a6ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gpuspec',
            unique_together={('used_port', 'gpu_index')},
        ),
        migrations.AddIndex(
            model_name='cpuspec',
            index=models.Index(fields=['used_port'], name='reverse_ssh_used_po_174541_idx'),
        ),
    ]
