# Generated by Django 4.1.2 on 2022-10-27 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedPort',
            fields=[
                ('reserved_port', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsedPort',
            fields=[
                ('used_port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='used_port', serialize=False, to='reverse_ssh_api.reservedport')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_total_size', models.IntegerField()),
                ('ram_free_size', models.IntegerField()),
                ('ram_used_size', models.IntegerField()),
                ('port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ram', to='reverse_ssh_api.usedport')),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_name', models.CharField(max_length=512)),
                ('gpu_total_size', models.IntegerField()),
                ('gpu_free_size', models.IntegerField()),
                ('gpu_used_size', models.IntegerField()),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpus', to='reverse_ssh_api.usedport')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_name', models.CharField(max_length=512)),
                ('cpu_clock', models.FloatField()),
                ('cpu_count', models.IntegerField()),
                ('port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='reverse_ssh_api.usedport')),
            ],
        ),
    ]
