# Generated by Django 4.1.2 on 2022-10-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_ssh_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='port',
            new_name='used_port',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='port',
            new_name='used_port',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='port',
            new_name='used_port',
        ),
    ]
