# Generated by Django 4.1.2 on 2022-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reverse_ssh_api', '0002_rename_port_cpu_used_port_rename_port_gpu_used_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='gpu_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gpu',
            unique_together={('used_port', 'gpu_index')},
        ),
    ]
